### ISSUE TITLE
Webui asking for auth without .htpasswd

### ISSUE THREAD

**Issue by zipeldiablo** [diameter/rtorrent-rutorrent#4]
Basically what's in the title, i didn't put a .htpasswd and still the ui is asking me for the password :/

**Comment by diameter** [comment]
Fixed.

**Comment by gpapin** [comment]
I think the issue is still here...

I removed those 2 lines in the nginx site conf to make it work: 

auth_basic "Restricted";
auth_basic_user_file /var/www/rutorrent/.htpasswd;
